title:       Open Room Lab
email:       your-email@example.com
description: Your description of the site here
author:      Pablo Moreno
baseurl:     "/pablo/"
url:         "https://eirol.github.io"

# Social Profiles
twitter_username:
github_username: PabloAMC
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:      kramdown
paginate:      5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
